name: survilleray
env:
    DATABASE_URL: "postgres://postgres@survilleray.railgun:5432/survilleray_development"
up:
  - homebrew:
    - openssl
  - go:
      version: 1.12
      modules: true
  - railgun
  - custom:
      name: Create PostgreSQL database
      met?: psql --username=postgres --host=survilleray.railgun -lqt | cut -d \| -f 1 | grep -qw survilleray_development
      meet: createdb --username=postgres --host=survilleray.railgun survilleray_development
  - custom:
      name: Build migration tool
      met?: bin/migrate
      meet: go build -o bin/migrate cmd/migrate/main.go
#   - database:
#       bootstrap: bin/migrate
#       migrate: bin/migrate
#       vendor: postgres
#       host: survilleray.railgun
#       user: postgres
#       password: ''
#       database: survilleray_development
  - python: 3.6.5
  - pip: [requirements.txt]
  - custom:
      name: Load dependencies
      met?: go mod tidy
      meet: go mod tidy
commands:
  test: go test -cover -race ./...
  survilleray: go run ./cmd/survilleray


