name: survilleray
up:
  - homebrew:
    - openssl
    - homebrew/cask/ngrok
    - golangci/tap/golangci-lint
    - golang-migrate
  - go:
      version: 1.12
      modules: true
  - python: 3.6.5
  - pip: [requirements.txt]
  - custom:
      name: Load dependencies
      met?: go mod tidy
      meet: go mod tidy
commands:
  test: go test -cover -race ./...
  survilleray: go run ./cmd/survilleray


