name: survilleray
env:
    DATABASE_URL: "postgres://postgres:docker@survilleray.railgun:5432/survilleray_development"
    DATABASE_TEST_URL: "postgres://postgres:docker@survilleray.railgun:5432/survilleray_test"
    PGPASSWORD: docker
up:
  - homebrew:
    - openssl
    - golangci/tap/golangci-lint
  - go:
      version: 1.13
      modules: true
  - railgun
  - custom:
      name: Create PostgreSQL database
      met?: psql --username=postgres --host=survilleray.railgun -lqt | cut -d \| -f 1 | grep -qw survilleray_development
      meet: createdb --username=postgres --host=survilleray.railgun survilleray_development
      name: Create PostgreSQL test database
      met?: psql --username=postgres --host=survilleray.railgun -lqt | cut -d \| -f 1 | grep -qw survilleray_test
      meet: createdb --username=postgres --host=survilleray.railgun survilleray_test
  - custom:
      name: Build command line tools
      met?: test -f "bin/survilleray"
      meet: go build -o bin/survilleray cmd/survilleray/main.go
  - custom:
      name: Load dependencies
      met?: go mod tidy
      meet: go mod tidy
commands:
  acquire: bin/survilleray acquire
  build: go build -o bin/survilleray cmd/survilleray/main.go
  collect: bin/survilleray collect
  db:create:
    desc: "Drop current database"
    run:  createdb --username=postgres --host=survilleray.railgun survilleray_development
  db:drop:
    desc: "Drop current database"
    run:  dropdb --username=postgres --host=survilleray.railgun survilleray_development
  db:migrate:
    desc: "Run all migrations"
    run: bin/survilleray migrate
  lint: golangci-lint run
  schedule: bin/survilleray schedule
  test: DATABASE_URL=$DATABASE_TEST_URL go test -cover -race ./...
  vectorize: bin/survilleray vectorize



