name: survilleray
env:
    DATABASE_URL: "postgres://postgres:docker@survilleray.railgun:5432/survilleray_development"
    PGPASSWORD: docker
up:
  - homebrew:
    - openssl
    - golangci/tap/golangci-lint
  - go:
      version: 1.12
      modules: true
  - railgun
  - custom:
      name: Create PostgreSQL database
      met?: psql --username=postgres --host=survilleray.railgun -lqt | cut -d \| -f 1 | grep -qw survilleray_development
      meet: createdb --username=postgres --host=survilleray.railgun survilleray_development
  - custom:
      name: Build command line tools
      met?: test -f "bin/survilleray"
      meet: go build -o bin/survilleray cmd/migrate/main.go
  - custom:
      name: Load dependencies
      met?: go mod tidy
      meet: go mod tidy
commands:
  test: go test -cover -race ./...
  lint: golangci-lint run
  build: go build -o bin/survilleray cmd/survilleray/main.go
  db:migrate:
    desc: "Run all migrations"
    run: bin/survilleray migrate


