# https://development.shopify.io/tools/dev/railgun/Railgun-Config
name: survilleray

vm:
  image:      /opt/dev/misc/railgun-images/default
  ip_address: 192.168.64.81
  memory:     2G
  cores:      2

volumes:
  root:  '2G'

services:
  - nginx

custom_services:
    - postgresql:
        healthcheck_port: 5432
        image: 'docker.io/kartoza/postgis:latest'
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASS: docker

hostnames:
  - survilleray.myshopify.io: { proxy_to_host_port: 9602 }

