name: Go
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgresql:
        image: docker.io/kartoza/postgis:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASS: docker
          POSTGRES_DBNAME: survilleray_test
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build -v -o ./bin/survilleray ./cmd/survilleray/main.go

    - name: Test
      env:

        DATABASE_URL: postgres://postgres:docker@127.0.0.1:${{ job.services.mysql.ports[5432] }}/survilleray_test?sslmode=disable
      run: go test -cover -race ./...